name: zenodraft
on:
  # Trigger manually
  workflow_dispatch

jobs:
  publish:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the contents of your repository
          uses: actions/checkout@v3
        - name: Convert CITATION.cff to .zenodo.citation.json
          uses: citation-file-format/cffconvert-github-action@2.0.0
          with:
            args: "--infile ./CITATION.cff --format zenodo --outfile .zenodo.citation.json"
        - name: Combine .zenodo.citation.json with .zenodo.extras.json
          run: |
            cat .zenodo.citation.json .zenodo.extras.json | jq -s add > .zenodo.json
        - name: Create a draft snapshot of the repository contents as a new
                version in a new collection on Zenodo using metadata
                from file .zenodo.json
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_ACCESS_TOKEN }}
          uses: zenodraft/action@0.10.0
          with:
            metadata: .zenodo.json
            publish: false
            sandbox: false
